### ISSUE TITLE
Improve account management

### ISSUE THREAD

**Issue by mattcoley** [HubSpot/hubspot-cms-tools#207] opened 2020-05-20 14:52 UTC
It would be ideal to never have to edit the `hubspot.config.yml` file. The `hs auth` command went a long way towards this goal by enabling creation of accounts, however once those accounts are created, you need to edit the config file to manage the accounts. Ideally there would be additional commands to list current accounts, switch main account, and delete an account.

**Comment by williamspiro** [comment] 2020-05-20 16:00
This might partially be a dupe of https://github.com/HubSpot/hubspot-cms-tools/issues/27

**Closed** 2020-05-20 16:11 UTC
